                                     WEB SCRAPING – ASSIGNMENT 4

Scrape the details of most viewed videos on YouTube from Wikipedia. Url
= https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:
A)Rank
B) Name
C) Artist
D) Upload date
E) Views

In [2]:
import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import requests
import os
from selenium.webdriver.common.by import By
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

import requests

import re

In [4]:
driver = webdriver.Chrome()
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

Rank=[]
Name=[]
Artist=[]
Up_Date=[]
Views=[]

In [17]:
nm = driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[1]')
Name=[]
for i in nm:
    if i.text is None :
        Name.append("--") 
    else:
        Name.append(i.text)
print(len(Name),Name)

30 ['"Baby Shark Dance"[7]', '"Despacito"[10]', '"Johny Johny Yes Papa"[18]', '"Bath Song"[19]', '"See You Again"[20]', '"Shape of You"[25]', '"Wheels on the Bus"[28]', '"Phonics Song with Two Words"[29]', '"Uptown Funk"[30]', '"Gangnam Style"[31]', '"Learning Colors – Colorful Eggs on a Farm"[36]', '"Dame Tu Cosita"[37]', '"Masha and the Bear – Recipe for Disaster"[38]', '"Axel F"[39]', '"Baa Baa Black Sheep"[40]', '"Sugar"[41]', '"Lakdi Ki Kathi"[42]', '"Counting Stars"[43]', '"Roar"[44]', '"Waka Waka (This Time for Africa)"[45]', '"Shree Hanuman Chalisa"[46]', '"Humpty the train on a fruits ride"[47]', '"Sorry"[48]', '"Thinking Out Loud"[49]', '"Perfect"[50]', '"Dark Horse"[51]', '"Let Her Go"[52]', '"Faded"[53]', '"Girls Like You"[54]', '"Lean On"[55]']

In [19]:
At=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[2]')
Artist=[]

for i in At:
    if i.text is None :
        Artist.append("--") 
    else:
        Artist.append(i.text)
print(len(Artist),Artist)

30 ["Pinkfong Baby Shark - Kids' Songs & Stories", 'Luis Fonsi', "LooLoo Kids - Nursery Rhymes and Children's Songs", 'Cocomelon - Nursery Rhymes', 'Wiz Khalifa', 'Ed Sheeran', 'Cocomelon - Nursery Rhymes', 'ChuChu TV Nursery Rhymes & Kids Songs', 'Mark Ronson', 'Psy', 'Miroshka TV', 'Ultra Records', 'Get Movies', 'Crazy Frog', 'Cocomelon - Nursery Rhymes', 'Maroon 5', 'Jingle Toons', 'OneRepublic', 'Katy Perry', 'Shakira', 'T-Series Bhakti Sagar', 'Kiddiestv Hindi - Nursery Rhymes & Kids Songs', 'Justin Bieber', 'Ed Sheeran', 'Ed Sheeran', 'Katy Perry', 'Passenger', 'Alan Walker', 'Maroon 5', 'Major Lazer Official']

In [21]:
date=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[4]')
Up_Date=[]

for i in date:
    if i.text is None :
        Up_Date.append("--") 
    else:
        Up_Date.append(i.text)
print(len(Up_Date),Up_Date)

30 ['June 17, 2016', 'January 12, 2017', 'October 8, 2016', 'May 2, 2018', 'April 6, 2015', 'January 30, 2017', 'May 24, 2018', 'March 6, 2014', 'November 19, 2014', 'July 15, 2012', 'February 27, 2018', 'April 5, 2018', 'January 31, 2012', 'June 16, 2009', 'June 25, 2018', 'January 14, 2015', 'June 14, 2018', 'May 31, 2013', 'September 5, 2013', 'June 4, 2010', 'May 10, 2011', 'January 26, 2018', 'October 22, 2015', 'October 7, 2014', 'November 9, 2017', 'February 20, 2014', 'July 25, 2012', 'December 3, 2015', 'May 31, 2018', 'March 22, 2015']

In [22]:
v=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[3]')
Views=[]

for i in v:
    if i.text is None :
        Views.append("--") 
    else:
        Views.append(i.text)
print(len(Views),Views)

30 ['14.52', '8.44', '6.91', '6.70', '6.27', '6.26', '6.13', '5.80', '5.23', '5.15', '5.11', '4.63', '4.58', '4.54', '4.05', '4.05', '4.04', '4.02', '4.00', '3.93', '3.84', '3.81', '3.80', '3.77', '3.74', '3.72', '3.66', '3.63', '3.61', '3.60']

In [26]:
import pandas as pd
Ytube_Video=pd.DataFrame([])

Ytube_Video['Video Title']=Name
Ytube_Video['Artist']=Artist
Ytube_Video['Up_Date']=Up_Date
Ytube_Video['Views In Bllion']=Views
Ytube_Video

,Video Title,Artist,Up_Date,Views In Bllion
0,"""Baby Shark Dance""[7]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",14.52
1,"""Despacito""[10]",Luis Fonsi,"January 12, 2017",8.44
2,"""Johny Johny Yes Papa""[18]",LooLoo Kids - Nursery Rhymes and Children's Songs,"October 8, 2016",6.91
3,"""Bath Song""[19]",Cocomelon - Nursery Rhymes,"May 2, 2018",6.70
4,"""See You Again""[20]",Wiz Khalifa,"April 6, 2015",6.27
5,"""Shape of You""[25]",Ed Sheeran,"January 30, 2017",6.26
6,"""Wheels on the Bus""[28]",Cocomelon - Nursery Rhymes,"May 24, 2018",6.13
7,"""Phonics Song with Two Words""[29]",ChuChu TV Nursery Rhymes & Kids Songs,"March 6, 2014",5.80
8,"""Uptown Funk""[30]",Mark Ronson,"November 19, 2014",5.23
9,"""Gangnam Style""[31]",Psy,"July 15, 2012",5.15
10,"""Learning Colors – Colorful Eggs on a Farm""[36]",Miroshka TV,"February 27, 2018",5.11
11,"""Dame Tu Cosita""[37]",Ultra Records,"April 5, 2018",4.63
12,"""Masha and the Bear – Recipe for Disaster""[38]",Get Movies,"January 31, 2012",4.58
13,"""Axel F""[39]",Crazy Frog,"June 16, 2009",4.54
14,"""Baa Baa Black Sheep""[40]",Cocomelon - Nursery Rhymes,"June 25, 2018",4.05
15,"""Sugar""[41]",Maroon 5,"January 14, 2015",4.05
16,"""Lakdi Ki Kathi""[42]",Jingle Toons,"June 14, 2018",4.04
17,"""Counting Stars""[43]",OneRepublic,"May 31, 2013",4.02
18,"""Roar""[44]",Katy Perry,"September 5, 2013",4.00
19,"""Waka Waka (This Time for Africa)""[45]",Shakira,"June 4, 2010",3.93
20,"""Shree Hanuman Chalisa""[46]",T-Series Bhakti Sagar,"May 10, 2011",3.84
21,"""Humpty the train on a fruits ride""[47]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,"January 26, 2018",3.81
22,"""Sorry""[48]",Justin Bieber,"October 22, 2015",3.80
23,"""Thinking Out Loud""[49]",Ed Sheeran,"October 7, 2014",3.77
24,"""Perfect""[50]",Ed Sheeran,"November 9, 2017",3.74
25,"""Dark Horse""[51]",Katy Perry,"February 20, 2014",3.72
26,"""Let Her Go""[52]",Passenger,"July 25, 2012",3.66
27,"""Faded""[53]",Alan Walker,"December 3, 2015",3.63
28,"""Girls Like You""[54]",Maroon 5,"May 31, 2018",3.61
29,"""Lean On""[55]",Major Lazer Official,"March 22, 2015",3.60

Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Series
B) Place
C) Date
D) Time

In [43]:
import time
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import requests
import os
from selenium.webdriver.common.by import By
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

import requests

import re

driver = webdriver.Chrome()
driver.get("https://www.bcci.tv/fixtures?platform=international&type=men")


Team=[]




tm=driver.find_elements(By.XPATH,'//div[@class="match-card-middle d-flex"]')
time.sleep(3)

for i in tm:
    if i.text is None :
        Team.append("--") 
    else:
        Team.append(i.text)
print(len(Team),Team)

5 ['Canada\nIndia', 'India Women\nSouth Africa Women', 'India Women\nSouth Africa Women', 'India Women\nSouth Africa Women', 'India Women\nSouth Africa Women']

In [36]:
DT=driver.find_elements(By.XPATH,'//div[@class="match-date-info"]')
Date_Time =[]

for i in DT:
    if i.text is None :
        Date_Time.append("--") 
    else:
        Date_Time.append(i.text)
print(len(Date_Time),Date_Time)

5 ['15 Jun\n20:00 IST', '16 Jun\n13:30 IST', '19 Jun\n13:30 IST', '23 Jun\n13:30 IST', '28 Jun\n9:30 IST']

In [38]:
P=driver.find_elements(By.XPATH,'//div[@class="match-venue ng-scope"]')
Place=[]
for i in P:
    if i.text is None :
        Place.append("--") 
    else:
        Place.append(i.text)
print(len(Place),Place)

5 ['Central Broward Park & Broward County Stadium, Lauderhill, Florida', 'M Chinnaswamy Stadium, Bengaluru', 'M Chinnaswamy Stadium, Bengaluru', 'M Chinnaswamy Stadium, Bengaluru', 'MA Chidambaram Stadium, Chennai']

In [39]:
T=driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope odi-tag"]')
Test=[]

for i in T:
    if i.text is None :
        Test.append("--") 
    else:
        Test.append(i.text)
print(len(Test),Test)

6 ['1st ODI', '', '2nd ODI', '', '3rd ODI', '']

In [46]:
Fixtures=pd.DataFrame([])
Fixtures['Team']=Team
Fixtures['Date_Time']=Date_Time
#Fixtures['Test']=Test
Fixtures['Place']=Place
Fixtures

,Team,Date_Time,Place
0,Canada\nIndia,15 Jun\n20:00 IST,"Central Broward Park & Broward County Stadium,..."
1,India Women\nSouth Africa Women,16 Jun\n13:30 IST,"M Chinnaswamy Stadium, Bengaluru"
2,India Women\nSouth Africa Women,19 Jun\n13:30 IST,"M Chinnaswamy Stadium, Bengaluru"
3,India Women\nSouth Africa Women,23 Jun\n13:30 IST,"M Chinnaswamy Stadium, Bengaluru"
4,India Women\nSouth Africa Women,28 Jun\n9:30 IST,"MA Chidambaram Stadium, Chennai"

Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details: A) Rank
B) State
C) GSDP(18-19)- at current prices
D) GSDP(19-20)- at current prices
E) Share(18-19)
F) GDP($ billion)

In [51]:
import time
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import requests
import os
from selenium.webdriver.common.by import By
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

import requests

import re

driver = webdriver.Chrome()
driver.get("https://www.statisticstimes.com/economy/india/indian-states-gdp.php")




GSDP_Current=[]
GSDP_Previous=[]
Share=[]



r=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[1]')
Rank=[]

for i in r:
    if i.text is None :
        Rank.append("--") 
    else:
        Rank.append(i.text)
print(len(Rank),Rank)

33 ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33']

In [52]:
St=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[2]')
State =[]

for i in St:
    if i.text is None :
        State.append("--") 
    else:
        State.append(i.text)
print(len(State),State)

33 ['Maharashtra', 'Tamil Nadu', 'Karnataka', 'Uttar Pradesh', 'Gujarat', 'West Bengal', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Odisha', 'Bihar', 'Punjab', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Sikkim', 'Manipur', 'Arunachal Pradesh', 'Nagaland', 'Mizoram', 'Andaman & Nicobar Islands']

In [53]:
gdpc=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[3]')
GDPC=[]

for i in gdpc:
    if i.text is None :
        GDPC.append("--") 
    else:
        GDPC.append(i.text)
print(len(GDPC),GDPC)

33 ['-', '2,700,109', '2,500,733', '2,547,861', '-', '1,700,939', '1,524,030', '1,439,674', '1,463,960', '1,363,327', '-', '1,107,746', '1,095,535', '832,790', '-', '736,423', '565,401', '505,887', '-', '346,206', '246,465', '207,430', '-', '-', '-', '-', '47,381', '-', '-', '-', '-', '-', '-']

In [54]:
gdpp=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[4]')
GDPP=[]

for i in gdpp:
    if i.text is None :
        GDPP.append("--") 
    else:
        GDPP.append(i.text)
print(len(GDPP),GDPP)

33 ['-', '2,364,514', '2,269,995', '2,258,040', '2,230,609', '1,531,758', '1,365,849', '1,303,524', '1,308,034', '1,246,471', '1,046,188', '1,014,688', '984,055', '753,177', '751,396', '676,164', '493,167', '464,399', '393,722', '303,781', '224,226', '191,728', '93,672', '72,636', '54,285', '49,643', '42,697', '42,756', '-', '39,630', '35,643', '-', '-']

In [58]:
shr=driver.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[6]")
for i in shr:
    if i.text is None :
        Share.append("--") 
    else:
        Share.append(i.text)
print(len(Share),Share)

33 ['13.17%', '8.78%', '8.38%', '8.37%', '8.17%', '5.63%', '5.06%', '4.87%', '4.76%', '4.63%', '3.96%', '3.73%', '3.68%', '2.81%', '2.76%', '2.62%', '1.74%', '1.74%', '1.52%', '1.13%', '0.82%', '0.73%', '0.36%', '0.27%', '0.20%', '0.19%', '0.16%', '0.16%', '0.16%', '0.15%', '0.13%', '0.12%', '0.04%']

In [59]:
State_GDP=pd.DataFrame([])
State_GDP['Rank']=Rank[:33]
State_GDP['State']=State[:33]
State_GDP['GSDP_Current']=GDPC[:33]
State_GDP['GSDP_Previous']=GDPP[:33]
State_GDP['Share In GDP']=Share[:33]
State_GDP

   Rank                      State GSDP_Current GSDP_Previous Share In GDP
0     1                Maharashtra            -             -       13.17%
1     2                 Tamil Nadu    2,700,109     2,364,514        8.78%
2     3                  Karnataka    2,500,733     2,269,995        8.38%
3     4              Uttar Pradesh    2,547,861     2,258,040        8.37%
4     5                    Gujarat            -     2,230,609        8.17%
5     6                West Bengal    1,700,939     1,531,758        5.63%
6     7                  Rajasthan    1,524,030     1,365,849        5.06%
7     8             Andhra Pradesh    1,439,674     1,303,524        4.87%
8     9                  Telangana    1,463,960     1,308,034        4.76%
9    10             Madhya Pradesh    1,363,327     1,246,471        4.63%
10   11                     Kerala            -     1,046,188        3.96%
11   12                      Delhi    1,107,746     1,014,688        3.73%
12   13                    Haryana    1,095,535       984,055        3.68%
13   14                     Odisha      832,790       753,177        2.81%
14   15                      Bihar            -       751,396        2.76%
15   16                     Punjab      736,423       676,164        2.62%
16   17                      Assam      565,401       493,167        1.74%
17   18               Chhattisgarh      505,887       464,399        1.74%
18   19                  Jharkhand            -       393,722        1.52%
19   20                Uttarakhand      346,206       303,781        1.13%
20   21            Jammu & Kashmir      246,465       224,226        0.82%
21   22           Himachal Pradesh      207,430       191,728        0.73%
22   23                        Goa            -        93,672        0.36%
23   24                    Tripura            -        72,636        0.27%
24   25                 Chandigarh            -        54,285        0.20%
25   26                 Puducherry            -        49,643        0.19%
26   27                  Meghalaya       47,381        42,697        0.16%
27   28                     Sikkim            -        42,756        0.16%
28   29                    Manipur            -             -        0.16%
29   30          Arunachal Pradesh            -        39,630        0.15%
30   31                   Nagaland            -        35,643        0.13%
31   32                    Mizoram            -             -        0.12%
32   33  Andaman & Nicobar Islands            -             -        0.04%

Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [60]:
import time
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import requests
import os
from selenium.webdriver.common.by import By
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

import requests

import re

driver = webdriver.Chrome()
driver.get("https://github.com/trending")

In [61]:
RN=driver.find_elements(By.XPATH,'//article[@class="Box-row"]/h2')
Repository_Name =[]

for i in RN:
    if i.text is None :
        Repository_Name.append("--") 
    else:
        Repository_Name.append(i.text)
print(len(Repository_Name),Repository_Name)

14 ['immich-app / immich', 'EricLBuehler / mistral.rs', 'gchq / CyberChef', 'huggingface / diffusers', 'fchollet / ARC-AGI', 'warpdotdev / Warp', 'LazyVim / LazyVim', 'codecrafters-io / build-your-own-x', 'datastrato / gravitino', 'goldmansachs / gs-quant', 'solana-labs / solana-program-library', 'DaoCloud / public-image-mirror', 'IDEA-Research / GroundingDINO', 'microsoft / playwright']

In [62]:
Description=[]
 
des=driver.find_elements(By.XPATH,'//article[@class="Box-row"]/p')
for i in des:
    if i.text is None :
        Description.append("--") 
    else:
        Description.append(i.text)
print(len(Description),Description)

14 ['High performance self-hosted photo and video management solution.', 'Blazingly fast LLM inference.', 'The Cyber Swiss Army Knife - a web app for encryption, encoding, compression and data analysis', '🤗 Diffusers: State-of-the-art diffusion models for image and audio generation in PyTorch and FLAX.', 'The Abstraction and Reasoning Corpus', 'Warp is a modern, Rust-based terminal with AI built in so you and your team can build great software, faster.', 'Neovim config for the lazy', 'Master programming by recreating your favorite technologies from scratch.', "World's most powerful open data catalog for building a high-performance, geo-distributed and federated metadata lake.", 'Python toolkit for quantitative finance', 'A collection of Solana programs maintained by Solana Labs', '很多镜像都在国外。比如 gcr 。国内下载很慢，需要加速。', 'Official implementation of the paper "Grounding DINO: Marrying DINO with Grounded Pre-Training for Open-Set Object Detection"', 'Playwright is a framework for Web Testing and Automation. It allows testing Chromium, Firefox and WebKit with a single API.']

In [ ]:
L=driver.find_elements(By.XPATH,'//article[@class="Box-row"]/div[2]/span')
Language=[]
for i in L:
    if i.text is None :
        Language.append("NAN") 
    else:
        Language.append(i.text)
print(len(Language),Language)

In [63]:
ml=driver.find_elements(By.XPATH,'//article[@class="Box-row"]/div[2]/a')
Muted_Link=[]
for i in ml:
    if i.text is None :
        Muted_Link.append("NAN") 
    else:
        Muted_Link.append(i.text)
print(len(Muted_Link),Muted_Link)

28 ['36,066', '1,704', '2,399', '173', '26,225', '3,014', '23,402', '4,821', '2,354', '419', '19,683', '320', '14,737', '1,007', '273,500', '25,800', '513', '183', '2,918', '514', '3,162', '1,921', '2,006', '265', '5,369', '564', '63,039', '3,411']

In [67]:
Trending_Repository=pd.DataFrame([])
Trending_Repository['Name']=Repository_Name[:14]
Trending_Repository['Description']=Description[:14]
#Trending_Repository['Language']=Language[:22]
Trending_Repository['Conutrybuted']=Muted_Link[:14]

Trending_Repository

,Name,Description,Conutrybuted
0,immich-app / immich,High performance self-hosted photo and video m...,"36,066"
1,EricLBuehler / mistral.rs,Blazingly fast LLM inference.,"1,704"
2,gchq / CyberChef,The Cyber Swiss Army Knife - a web app for enc...,"2,399"
3,huggingface / diffusers,🤗 Diffusers: State-of-the-art diffusion models...,173
4,fchollet / ARC-AGI,The Abstraction and Reasoning Corpus,"26,225"
5,warpdotdev / Warp,"Warp is a modern, Rust-based terminal with AI ...","3,014"
6,LazyVim / LazyVim,Neovim config for the lazy,"23,402"
7,codecrafters-io / build-your-own-x,Master programming by recreating your favorite...,"4,821"
8,datastrato / gravitino,World's most powerful open data catalog for bu...,"2,354"
9,goldmansachs / gs-quant,Python toolkit for quantitative finance,419
10,solana-labs / solana-program-library,A collection of Solana programs maintained by ...,"19,683"
11,DaoCloud / public-image-mirror,很多镜像都在国外。比如 gcr 。国内下载很慢，需要加速。,320
12,IDEA-Research / GroundingDINO,"Official implementation of the paper ""Groundin...","14,737"
13,microsoft / playwright,Playwright is a framework for Web Testing and ...,"1,007"

Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board

In [ ]:
import time
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import requests
import os
from selenium.webdriver.common.by import By
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

import requests

import re

driver = webdriver.Chrome()
driver.get("https://www.billboard.com/")

Song_Name =[]
Singer=[]
rank=[]
Last_Week=[]
Weeks_on_board=[]